spring:
  profiles: 
    active: prod
    
---

spring:
  profiles: dev
  
startRoute: timer:hello?period=10s
fromRoute: file:data/input/dev?delete=true&readLock=none
toRoute1: file:data/output

message: DEV Environment
    
---

spring:
  profiles: stage

startRoute: timer:hello?period=10s
fromRoute: file:data/stage/input?delete=true&readLock=none
toRoute1: file:data/output

message: STAGE Environment

---

spring:
  profiles: prod

startRoute: timer:hello?period=10s
fromRoute: file:data/prod/input?delete=true&readLock=none
toRoute1: file:data/output

message: PROD Environment

---